In [1]:
# 导包
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

# 导入线性回归对象
from sklearn.linear_model import LinearRegression

from IPython.core.interactiveshell import InteractiveShell # 这个对象设置所有行全部输出

# 设置该对象ast_node_interactivity属性的值为all，表示在notebook下每一行有输出的代码全部输出运算结果
InteractiveShell.ast_node_interactivity = "all" 

# 解决坐标轴刻度负号乱码
plt.rcParams['axes.unicode_minus'] = False

# 基本参数设置
plt.rcParams['font.sans-serif']=['Simhei']
plt.rcParams['axes.unicode_minus']=False

In [2]:
# 设置随机种子
ranges = np.random.RandomState(1)

# 100个[0,5)的随机数
x = 5 * ranges.rand(100)

# 真实规律的标签取值
y = 2 * x - 5 + ranges.randn(100)

x, y

(array([2.08511002e+00, 3.60162247e+00, 5.71874087e-04, 1.51166286e+00,
        7.33779454e-01, 4.61692974e-01, 9.31301057e-01, 1.72780364e+00,
        1.98383737e+00, 2.69408367e+00, 2.09597257e+00, 3.42609750e+00,
        1.02226125e+00, 4.39058718e+00, 1.36937966e-01, 3.35233755e+00,
        2.08652401e+00, 2.79344914e+00, 7.01934693e-01, 9.90507445e-01,
        4.00372284e+00, 4.84130788e+00, 1.56712089e+00, 3.46161308e+00,
        4.38194576e+00, 4.47303332e+00, 4.25221057e-01, 1.95273916e-01,
        8.49152098e-01, 4.39071252e+00, 4.91734169e-01, 2.10553813e+00,
        4.78944765e+00, 2.66582642e+00, 3.45938557e+00, 1.57757816e+00,
        3.43250464e+00, 4.17312836e+00, 9.14413867e-02, 3.75072157e+00,
        4.94430544e+00, 3.74082827e+00, 1.40221996e+00, 3.94639664e+00,
        5.16130033e-01, 2.23946763e+00, 4.54297752e+00, 1.46807074e+00,
        1.43887669e+00, 6.50142861e-01, 9.68347894e-02, 3.39417766e+00,
        1.05814058e+00, 1.32773330e+00, 2.45786580e+00, 2.66812726e-01,
        2.87058803e+00, 7.33642875e-01, 2.94652768e+00, 3.49879180e+00,
        5.11672144e-01, 2.07027994e+00, 3.47200079e+00, 2.07089635e+00,
        2.49767295e-01, 2.67948203e+00, 3.31897323e+00, 2.57444556e+00,
        4.72297378e+00, 2.93277520e+00, 4.51700958e+00, 6.87373521e-01,
        6.96381736e-01, 4.03695644e+00, 1.98838418e+00, 8.26770986e-01,
        4.63754290e+00, 1.73882930e+00, 3.75406052e+00, 3.62998993e+00,
        4.41653046e+00, 3.11836104e+00, 3.75471217e+00, 1.74449171e+00,
        1.34963946e+00, 4.47943109e+00, 2.14045595e+00, 4.82420024e+00,
        3.31720749e+00, 3.10847860e+00, 5.73729865e-01, 4.74744629e+00,
        2.24956067e+00, 2.89194807e+00, 2.04068401e+00, 1.18513490e+00,
        4.51689760e+00, 2.86839743e+00, 1.43516352e-02, 3.08572457e+00]),
 array([-0.51414501,  0.18104372, -5.30506026, -1.14869963, -3.30234636,
        -3.31460287, -3.35972603, -1.7451508 , -0.84576387,  0.79821899,
        -0.60975514,  1.97120365, -3.62613979,  4.15873815, -4.6043028 ,
         2.83415901,  0.3719659 ,  0.7720547 , -3.97141556, -3.65771552,
         3.43094004,  4.75995583, -2.20961189,  1.96682301,  3.14389068,
         4.64409867, -4.59668645, -3.38494446, -2.89820416,  4.37500356,
        -5.11144351, -0.61954132,  5.31945175, -0.62204775,  1.65255263,
        -1.81222914,  0.49189196,  3.66141611, -3.97095658,  1.64192721,
         5.23915687,  1.16937313, -2.23425559,  1.27702093, -2.84632223,
        -0.1121642 ,  4.06133808, -2.83902014, -0.84849068, -1.73261253,
        -6.66431229,  3.02451936, -1.25606809, -2.00652171, -1.28353644,
        -3.60302923,  0.56025575, -4.13663488, -0.33700277,  2.5481211 ,
        -3.18384885, -1.48297085,  2.46457791, -2.00254869, -3.69860438,
         0.40553136,  1.45137668,  0.04714525,  5.31483372,  1.61596204,
         4.56348448, -3.48755175, -3.5294154 ,  3.69229315, -0.79073707,
        -2.66390662,  3.96496903, -3.95717917,  3.54694563,  4.4469595 ,
         4.27442536,  1.13656684,  2.3729796 , -1.63007077, -2.28331167,
         2.83684345, -1.23618256,  3.65137364,  1.88321414,  0.92031605,
        -3.35732895,  4.32018943,  0.48545652,  0.99743005,  1.27206776,
        -4.52609112,  3.38687852,  1.63828176, -2.44297102,  0.92281436]))

In [3]:
# 构造为dataframe
X = pd.DataFrame(x)
Y = pd.DataFrame(y)

X, Y

(           0
 0   2.085110
 1   3.601622
 2   0.000572
 3   1.511663
 4   0.733779
 ..       ...
 95  1.185135
 96  4.516898
 97  2.868397
 98  0.014352
 99  3.085725

 [100 rows x 1 columns],
            0
 0  -0.514145
 1   0.181044
 2  -5.305060
 3  -1.148700
 4  -3.302346
 ..       ...
 95 -4.526091
 96  3.386879
 97  1.638282
 98 -2.442971
 99  0.922814

 [100 rows x 1 columns])

In [4]:
# 添加一列全为1的列,表示截距
ex = pd.DataFrame(np.ones([100,1]))
ex

      0
0   1.0
1   1.0
2   1.0
3   1.0
4   1.0
..  ...
95  1.0
96  1.0
97  1.0
98  1.0
99  1.0

[100 rows x 1 columns]

In [5]:
# 轴1方向构造最终“数据集”
data = pd.concat([ex,X,Y],axis=1)
data

      0         0         0
0   1.0  2.085110 -0.514145
1   1.0  3.601622  0.181044
2   1.0  0.000572 -5.305060
3   1.0  1.511663 -1.148700
4   1.0  0.733779 -3.302346
..  ...       ...       ...
95  1.0  1.185135 -4.526091
96  1.0  4.516898  3.386879
97  1.0  2.868397  1.638282
98  1.0  0.014352 -2.442971
99  1.0  3.085725  0.922814

[100 rows x 3 columns]

In [6]:
# 创建线性回归器对象
reg = LinearRegression()

# 训练线性回归模型
reg.fit(data.iloc[:,:-1].values,data.iloc[:,-1].values)

reg.coef_ # 查看方程系数
reg.intercept_ # 查看系数

LinearRegression()

array([0.        , 1.93698502])

np.float64(-4.763042745851091)

In [7]:
# 导入MSE计算公式和R^2计算公式
from sklearn.metrics import mean_squared_error,r2_score

# 获取预测值
yhat = reg.predict(data.iloc[:,:-1])

# 获取标签观察值
y = data.iloc[:,-1].values

# 计算MSE
mean_squared_error(y,yhat)

# 计算R^2
r2_score(y,yhat)

0.7997618656011583

0.9104352692515009